# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 04:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeletemeBotSingleton',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_run', models.DateTimeField()),
                ('name', models.CharField(max_length=20)),
                ('default_delay', models.DurationField()),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'deleteme_bot_singleton',
            },
        ),
        migrations.CreateModel(
            name='RedditComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(help_text='Do not include type prefix', max_length=10, unique=True)),
                ('delete_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'reddit_comment',
            },
        ),
        migrations.CreateModel(
            name='RedditUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(max_length=80, unique=True)),
                ('strikes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'reddit_user',
            },
        ),
        migrations.CreateModel(
            name='StateCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=80, unique=True)),
                ('expires', models.DateTimeField(default=datetime.datetime(2016, 12, 19, 10, 54, 57, 814957, tzinfo=utc))),
            ],
            options={
                'db_table': 'state_code',
            },
        ),
        migrations.AddField(
            model_name='redditcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='deleteme_bot.RedditUser'),
        ),
    ]
