# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 23:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deleteme_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletemebotsingleton',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 7, 23, 2, 46, 212640)),
        ),
        migrations.AlterField(
            model_name='statecode',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 8, 0, 2, 46, 214352)),
        ),
    ]
