# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 23:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deleteme_bot', '0002_auto_20161207_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletemebotsingleton',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 7, 23, 26, 17, 702712)),
        ),
        migrations.AlterField(
            model_name='statecode',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 8, 0, 26, 17, 704082)),
        ),
        migrations.AlterModelTable(
            name='deletemebotsingleton',
            table='deleteme_bot_singleton',
        ),
        migrations.AlterModelTable(
            name='redditcomment',
            table='reddit_comment',
        ),
        migrations.AlterModelTable(
            name='reddituser',
            table='reddit_user',
        ),
        migrations.AlterModelTable(
            name='statecode',
            table='state_code',
        ),
    ]
